const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const http=require('node:http');
const {chromium}=require('playwright');
(async()=>{
  const root=path.join(__dirname,'dist');const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css'};
  const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(root)||!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',mime[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});
  try{const p=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
    await p.goto(`http://127.0.0.1:${server.address().port}/`);await p.locator('#evaluate').click();assert((await p.locator('#assessment').textContent()).includes('請補齊'));
    await p.locator('#demo').click();assert((await p.locator('#assessment').textContent()).includes('優先考慮 APD'));assert((await p.locator('#bags').textContent()).includes('IEXTRA1'));assert.equal(await p.locator('#rxWarnings .danger').count(),0);
    await p.locator('#reviewed').check();const download=p.waitForEvent('download');await p.locator('#download').click();const file=await download;assert.equal(file.suggestedFilename(),'PD-consultation.txt');const saved=await file.path();assert(fs.readFileSync(saved,'utf8').includes('示範個案'));
    await p.locator('[data-rx="hours"]').fill('7');await p.locator('[data-rx="hours"]').dispatchEvent('change');assert((await p.locator('#rxWarnings').textContent()).includes('14–16'));
    await p.locator('#demo').click();await p.locator('#weight').fill('61');assert(await p.locator('#prescriptionPanel').isHidden());
    await p.locator('#evaluate').click();await p.locator('[data-rx="mode"]').selectOption('CAPD');await p.locator('[data-row="0"][data-field="product"]').selectOption('I25D25LU');assert((await p.locator('#bags').textContent()).includes('I25D25LU'));
    await p.locator('#potassium').fill('6.8');await p.locator('#evaluate').click();assert((await p.locator('#assessment').textContent()).includes('急性狀況'));assert(await p.locator('#prescriptionPanel').isHidden());
    await p.locator('#demo').click();await p.locator('[data-stage="initial"]').click();await p.locator('#evaluate').click();assert((await p.locator('#assessment').textContent()).includes('尚無有效 PET'));assert(await p.locator('.pet-panel').isHidden());assert(await p.locator('#pdKtv').isHidden());assert(!(await p.locator('#assessment').textContent()).includes('總 weekly Kt/V'));await p.locator('#serumCr').fill('');await p.locator('#egfr').fill('');await p.locator('#ccr').fill('');await p.locator('#kru').fill('');await p.locator('#evaluate').click();assert((await p.locator('#assessment').textContent()).includes('初始腎功能資料'));
    await p.locator('#demo').click();await p.locator('#dp').fill('0.45');await p.locator('#preference').selectOption('either');await p.locator('#volume').selectOption('euvolemic');await p.locator('#evaluate').click();assert((await p.locator('#assessment').textContent()).includes('優先考慮 CAPD'));
    await p.locator('#demo').click();await p.locator('[data-stage="initial"]').click();assert(await p.locator('#infection').isHidden());await p.locator('#sym-appetite').check();await p.locator('#sym-nausea').check();assert(!(await p.locator('#sym-none').isChecked()));await p.locator('#evaluate').click();assert((await p.locator('#assessment').textContent()).includes('整體症狀嚴重度'));await p.locator('#symptomSeverity').selectOption('moderate');await p.locator('#symptomAttribution').selectOption('likely');await p.locator('#evaluate').click();assert((await p.locator('#assessment').textContent()).includes('食慾下降、噁心'));assert((await p.locator('#assessment').textContent()).includes('起始清除'));await p.locator('[data-rx="mode"]').selectOption('CAPD');await p.locator('#reviewed').check();const sxDownload=p.waitForEvent('download');await p.locator('#download').click();const sxFile=await sxDownload;const sxText=fs.readFileSync(await sxFile.path(),'utf8');assert(sxText.includes('食慾下降、噁心'));assert(sxText.includes('中度'));await p.locator('#sym-none').check();assert(!(await p.locator('#sym-nausea').isChecked()));assert(await p.locator('#symptomDetails').isHidden());await p.locator('#sym-encephalopathy').check();await p.locator('#evaluate').click();assert((await p.locator('#assessment').textContent()).includes('即時評估'));assert(await p.locator('#prescriptionPanel').isHidden());
    await p.locator('#demo').click();await p.locator('[data-stage="follow"]').click();assert(await p.locator('#infection').isVisible());await p.locator('#infection').check();await p.locator('#evaluate').click();assert((await p.locator('#assessment').textContent()).includes('疑似腹膜炎'));await p.locator('[data-stage="initial"]').click();await p.locator('#evaluate').click();assert(!(await p.locator('#assessment').textContent()).includes('疑似腹膜炎'));assert(await p.locator('#prescriptionPanel').isVisible());
    await p.locator('#demo').click();await p.locator('[data-stage="initial"]').click();await p.locator('#correctionDays').fill('5');await p.locator('#fluidGoalSafe').check();await p.locator('#evaluate').click();assert((await p.locator('#goalResults').textContent()).includes('1100 mL/day'));assert((await p.locator('#goalResults').textContent()).includes('治療後才能確認'));await p.locator('[data-rx="mode"]').selectOption('CAPD');await p.locator('#reviewed').check();const goalDownload=p.waitForEvent('download');await p.locator('#download').click();const goalText=fs.readFileSync(await (await goalDownload).path(),'utf8');assert(goalText.includes('淨 UF 目標：1100'));assert(goalText.includes('未宣稱整體達標'));await p.locator('#intake').fill('1700');assert(!(await p.locator('#fluidGoalSafe').isChecked()));assert(await p.locator('#prescriptionPanel').isHidden());await p.locator('#evaluate').click();assert((await p.locator('#goalResults').textContent()).includes('待醫師確認'));await p.locator('#volume').selectOption('depleted');await p.locator('#excessFluid').fill('0');await p.locator('#evaluate').click();assert((await p.locator('#goalResults').textContent()).includes('暫不提供自動脫水目標'));
    await p.setViewportSize({width:390,height:844});assert(!(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));
    assert.deepEqual(errors,[]);console.log('Browser PASS: missing data, APD recommendation, physician-reviewed export, timing validation, stale data, exact order code, acute routing, no-PET initiation, slow transport and mobile width.');
  }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1);});
