const assert=require('node:assert/strict');
const PD=require('./dist/engine.js');const C=require('./dist/catalog.js');
const d={stage:'initial',serumCr:8,egfr:6,age:65,height:165,weight:62,urine:600,volume:'euvolemic',symptom:'none',access:'healed',apdReady:'yes',capdReady:'yes',potassium:4.5,bicarb:24,fill:2000,calcium:'low',preference:'either',dose:'standard',sleep:8,longSolution:'auto',icoSafe:true};
let count=0;function test(name,fn){fn();count++;console.log('PASS',name);}
test('No PET needed for initiation',()=>{const a=PD.assess(d);assert.equal(a.missing.length,0);assert.equal(a.mode,'CAPD');assert.equal(a.pet,null);});
test('Zero urine is a value, missing urine blocks',()=>{assert.equal(PD.assess({...d,urine:0}).missing.length,0);assert(PD.assess({...d,urine:''}).missing.includes('每日尿量'));});
test('Acute K and new access route to human review',()=>{assert(PD.assess({...d,potassium:6.5}).blocks.length);assert(PD.assess({...d,access:'urgent'}).blocks.length);});
test('PET UF threshold respects concentration and volume',()=>{assert(PD.pet({dp:.8,petIn:2000,petOut:2099,petConcentration:'2.5'}).lowUf);assert(!PD.pet({dp:.8,petIn:2000,petOut:2100,petConcentration:'2.5'}).lowUf);assert(PD.pet({dp:.8,petIn:2000,petOut:2399,petConcentration:'4.25'}).lowUf);assert(!PD.pet({dp:.8,petIn:1500,petOut:1550,petConcentration:'2.5'}).lowUf);});
test('PET transport boundaries',()=>{for(const [x,t]of [[.499,'low'],[.5,'lowAvg'],[.65,'highAvg'],[.819,'highAvg'],[.82,'high']])assert.equal(PD.pet({dp:x}).transport,t);});
const pd={...d,stage:'pet',currentMode:'CAPD',uf:400,currentFill:2000,currentCycles:4,adherence:'good',petDate:'2026-10-01',petConcentration:'2.5',petIn:2000,petOut:2080,dp:.86,crCorrection:'yes',petClass:'auto',petIssue:'no'};
test('Fast transport recommends APD; slow recommends CAPD',()=>{assert.equal(PD.assess(pd).mode,'APD');assert.equal(PD.assess({...pd,dp:.45}).mode,'CAPD');});
test('Unavailable modality excluded',()=>{assert.equal(PD.assess({...pd,apdReady:'no'}).mode,'CAPD');assert(PD.assess({...d,apdReady:'no',capdReady:'no'}).blocks.length);});
test('Incremental requires renal clearance, not urine alone',()=>{assert(PD.assess({...d,dose:'incremental'}).missing.length);assert(PD.assess({...d,dose:'incremental',incrementalSafe:true,renalKtv:.8,volume:'overload'}).blocks.length);});
test('CAPD bag selection and daily totals',()=>{const a=PD.assess(d),rx=PD.initialRx(d,a),v=PD.validateRx(rx,d,a,C);assert.equal(v.total,8000);assert.equal(v.glucose,120);assert.equal(v.bags[0].product.code,'I15D20LU');assert.equal(v.bags[0].count,4);assert.equal(v.errors.length,0);});
test('Explicit larger single-use bag is retained',()=>{const a=PD.assess(d),rx=PD.initialRx(d,a);rx.rows[0].productCode='I15D25LU';const v=PD.validateRx(rx,d,a,C);assert(v.bags.some(x=>x.product.code==='I15D25LU'));});
test('CAPD schedule >24h invalid and ico max once daily',()=>{const a=PD.assess(d),rx=PD.initialRx(d,a);rx.rows[0].dwell=12;assert(PD.validateRx(rx,d,a,C).errors.length);rx.rows.forEach(r=>{r.kind='ico';r.dwell=6;});assert(PD.validateRx(rx,d,a,C).errors.some(x=>x.includes('每 24 小時一次')));});
test('APD bags include priming, last fill counted once',()=>{const a=PD.assess(pd),rx=PD.initialRx(pd,a);Object.assign(rx,{fillDrain:25,initialDrain:15,lastFillTime:10,prime:500});const v=PD.validateRx(rx,pd,a,C);assert.equal(v.total,12000);assert.equal(v.errors.length,0);assert.equal(v.bags.find(x=>x.product.code==='I15D50L').count,3);assert.equal(v.bags.find(x=>x.product.code==='IEXTRA1').count,1);});
test('Missing timing blocks APD export; impossible time detected',()=>{const a=PD.assess(pd),rx=PD.initialRx(pd,a);assert(PD.validateRx(rx,pd,a,C).errors.length);Object.assign(rx,{fillDrain:90,initialDrain:90,lastFillTime:90,prime:500});assert(PD.validateRx(rx,pd,a,C).errors.some(x=>x.includes('無有效留置')));});
test('Nutrineal not automatically selected and acidosis blocked',()=>{const a=PD.assess(d),rx=PD.initialRx(d,a);assert(!rx.rows.some(r=>r.kind==='aa'));rx.rows[0].kind='aa';assert(PD.validateRx(rx,{...d,bun:60,bicarb:18},a,C).errors.some(x=>x.includes('Nutrineal')));});


test('Initial requires baseline renal data but no Kt/V',()=>{assert(PD.assess({...d,serumCr:'',egfr:''}).missing.some(x=>x.includes('初始腎功能')));assert.equal(PD.assess({...d,renalKtv:'',pdKtv:''}).missing.length,0);assert.equal(PD.assess({...d,renalKtv:1,pdKtv:1.2}).ktv,null);});
 test('Measured clearance average and quality gate',()=>{assert.equal(PD.renal({...d,ccr:6,kru:2,collection:'valid'}).mean,4);assert.equal(PD.renal({...d,ccr:6,kru:2,collection:'unknown'}).mean,null);assert(PD.assess({...d,dose:'incremental',incrementalSafe:true,collection:'valid',ccr:6,kru:2}).missing.length===0);assert(PD.assess({...d,dose:'incremental',incrementalSafe:true,collection:'valid',ccr:6}).missing.length>0);assert(PD.assess({...d,dose:'incremental',incrementalSafe:true,collection:'valid',kru:0}).missing.length>0);});

test('Multiple symptoms guide clearance, not modality, and prevent low-dose template',()=>{const x={...d,symptoms:['appetite','nausea'],symptomSeverity:'moderate',symptomAttribution:'likely'};const a=PD.assess(x);assert.equal(a.mode,PD.assess(d).mode);assert(a.reasons.some(t=>t.includes('食慾下降、噁心')));assert(a.adjustments.some(t=>t.includes('初始')));assert(PD.assess({...x,dose:'incremental',collection:'valid',kru:3,incrementalSafe:true}).blocks.length);assert(PD.assess({...x,symptomSeverity:''}).missing.includes('整體症狀嚴重度'));assert(PD.assess({...x,symptomAttribution:''}).missing.includes('症狀臨床歸因評估'));assert(PD.assess({...d,symptoms:['none','nausea']}).blocks.length);assert(PD.assess({...d,symptoms:[]}).missing.length);});
test('Urgent uremic complications require acute review, even with missing data',()=>{for(const code of ['encephalopathy','pericarditis'])assert(PD.assess({...d,symptoms:[code],symptomSeverity:'',symptomAttribution:''}).blocks.some(t=>t.includes('即時評估')));});
test('Infection applies only after PD starts; unrelated symptoms do not imply poor clearance',()=>{assert.equal(PD.assess({...d,infection:true}).blocks.length,0);assert(PD.assess({...pd,infection:true}).blocks.some(t=>t.includes('腹膜炎')));const a=PD.assess({...d,symptoms:['fatigue'],symptomSeverity:'mild',symptomAttribution:'other'});assert(a.adjustments.some(t=>t.includes('其他原因')));assert(!a.adjustments.some(t=>t.includes('足夠的起始清除')));});
console.log(`${count} meaningful clinical and arithmetic checks passed`);
